package com.example.bluegrass.bluegrass.uppgift.managers;

import com.example.bluegrass.bluegrass.uppgift.repositories.HumanRepository;
import generated.Human;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
* Generated by Spring Data Generator on 31/05/2022
*/
@Component
public class HumanManager {

	private final HumanRepository humanRepository;

	@Autowired
	public HumanManager(HumanRepository humanRepository) {
		this.humanRepository = humanRepository;
	}

}
