package com.example.bluegrass.bluegrass.uppgift.managers;

import com.example.bluegrass.bluegrass.uppgift.repositories.WeatherDataRepository;
import generated.WeatherData;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
* Generated by Spring Data Generator on 31/05/2022
*/
@Component
public class WeatherDataManager {

	private final WeatherDataRepository weatherDataRepository;

	@Autowired
	public WeatherDataManager(WeatherDataRepository weatherDataRepository) {
		this.weatherDataRepository = weatherDataRepository;
	}

}
