package com.example.bluegrass.bluegrass.uppgift.repositories;

import generated.Human;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.data.querydsl.QuerydslPredicateExecutor;
import org.springframework.stereotype.Repository;

import java.util.Date;
import java.util.Optional;

/**
* Generated by Spring Data Generator on 31/05/2022
*/
@Repository
public interface HumanRepository extends JpaRepository<Human, Long>, JpaSpecificationExecutor<Human>, QuerydslPredicateExecutor<Human> {
    Human findByFirstNameAndLastNameAndHairColorAndBirthItem(String firstName, String lastName, String hairColor, Date birth);
    Optional<Human> findById(Long id);



}
